<?php
/**
 * @var $block DurableCode\ProductLabels\Block\Product\LabelRenderer
 */

$labelData = $block->getLabels();

if (empty($labelData)) {
    return;
}
?>

<?php foreach ($labelData as $label => $options):?>
    <span style="<?php foreach ($options as $option): ?>
        <?= $escaper->escapeHtmlAttr($block->getCss($option)) ?>
    <?php endforeach; ?>">
        <?= $escaper->escapeHtml($label) ?>
    </span>
    <br>
<?php endforeach; ?>
